export const meses = [
  "janeiro",
  "fevereiro",
  "março",
  "abril",
  "maio",
  "junho",
];

export const content = document.querySelector("#content");

export const element1 = document.getElementById("1");
export const element2 = document.getElementById("2");
export const element3 = document.getElementById("3");
export const element4 = document.getElementById("4");
export const element5 = document.getElementById("5");
export const element6 = document.getElementById("6");
export const element7 = document.getElementById("7");
export const element8 = document.getElementById("8");
export const element9 = document.getElementById("9");

export const products = {
  porcoesPestiscos: [
    {
      name: "301. Filé mignon gratinado",
      description: "Catupiry, gorgonzola e pão",
      alt: "Filé mignon gratinado",
      image: "1.png",
      price: "71.99",
    },
    {
      name: "302. Picanha ao alho ",
      description: "Acompanha mandioca R$ 71.99",
      alt: "Picanha ao alho ",
      image: "2.png",
      price: "Acompanha fritas R$ 68.99",
    },
    {
      name: "3021. Picanha ao alho ",
      description: "Acompanha fritas",
      alt: "Picanha ao alho ",
      image: "2.png",
      price: "68.99",
    },
    {
      name: "303.Filé mignon ao catupiry",
      description: "Acompanha mandioca",
      alt: "Filé mignon ao catupiry",
      image: "3.png",
      price: "67.99",
    },
    {
      name: "3031.Filé mignon ao catupiry",
      description: "Acompanha fritas",
      alt: "Filé mignon ao catupiry",
      image: "3.png",
      price: "64.99",
    },
    {
      name: "304 Filé mignon acebolado",
      description: "Acompanha mandioca",
      alt: "Filé mignon acebolado",
      image: "semimagem.png",
      price: "67.99",
    },
    {
      name: "304. Filé mignon acebolado",
      description: "Acompanha fritas",
      alt: "Filé mignon acebolado",
      image: "semimagem.png",
      price: "64.99",
    },
    {
      name: "305. Isca de frango à milanesa",
      description: "Servido com catupiry",
      alt: "Isca de frango à milanesa",
      image: "5.png",
      price: "35.99",
    },
    {
      name: "306. Frango à passarinho com alho",
      description: "Porção de frango à passarinho com alho",
      alt: "Frango à passarinho com alho",
      image: "6.png",
      price: "29.99",
    },
    {
      name: "307. Isca de tilápia à milanesa",
      description: "Servido com limão e molho especial",
      alt: "Isca de tilápia à milanesa",
      image: "7.png",
      price: "42.99",
    },
    {
      name: "308. Calabresa acebolado",
      description: "servido com pão fatiado",
      alt: "Calabresa acebolado",
      image: "8.png",
      price: "29.99",
    },
    {
      name: "309. Mandioca frita",
      description: "Porção inteira",
      alt: "Mandioca frita",
      image: "9.png",
      price: "24.99",
    },
    {
      name: "309. Mandioca frita",
      description: "Porção meia",
      alt: "Mandioca frita",
      image: "9.png",
      price: "14.99",
    },
    {
      name: "310. Fritas",
      description: "Porção inteira",
      alt: "Fritas",
      image: "10.png",
      price: "21.99",
    },
    {
      name: "310. Fritas",
      description: "Porção meia",
      alt: "Fritas",
      image: "10.png",
      price: "12.99",
    },
    {
      name: "311. Fritas especial",
      description: "com mix de queijos e bacon",
      alt: "Fritas especial",
      image: "11.png",
      price: "29.99",
    },
    {
      name: "312. Batata rústica",
      description: "servida com molho especial",
      alt: "Batata rústica",
      image: "12.png",
      price: "24.99",
    },
    {
      name: "313. Cebola empanada",
      description: "servida com molho especial",
      alt: "Cebola empanada",
      image: "13.png",
      price: "24.99",
    },
    {
      name: "314. Mini pastéis",
      description: "Carne e queijo - | 10 unidades |",
      alt: "Mini pastéis",
      image: "14.png",
      price: "27.99",
    },
    {
      name: "315. Bolinho de bacalhau",
      description: "Servido com limão e molho especial - | 10 unidades|",
      alt: "Bolinho de bacalhau",
      image: "15.png",
      price: "31.99",
    },
    {
      name: "316. Bolinho de mandioca",
      description: "Recheado com carne  - | 10 unidades|",
      alt: "Bolinho de mandioca",
      image: "16.png",
      price: "32.99",
    },
    {
      name: "317. Bolinho de mandioca",
      description: "Recheado com costela - | 10 unidades|",
      alt: "Bolinho de mandioca",
      image: "16.png",
      price: "32.99",
    },
    {
      name: "319. Salgadinhos fritos",
      description: "Salgadinhos fritos",
      alt: "Salgadinhos fritos",
      image: "17.png",
      price: "24.99",
    },
    {
      name: "320. Panceta",
      description: "Servida com vinagrete apimentado e mandioca",
      alt: "Panceta",
      image: "18.png",
      price: "34.99",
    },
    {
      name: "321. Torresmo de rolo",
      description: "Acompanha mandioca e pimenta biquinho",
      alt: "Torresmo de rolo",
      image: "19.png",
      price: "42.99",
    },
    {
      name: "322. Medalhão de frango com bacon",
      description: "Acompanha mandioca",
      alt: "Medalhão de frango com bacon",
      image: "20.png",
      price: "37.99",
    },
    {
      name: "323. Medalhão de mandioca com bacon",
      description: "Acompanha anéis de cebola empanados",
      alt: "Medalhão de mandioca com bacon",
      image: "21.png",
      price: "29.99",
    },
    {
      name: "324. Tábua de frios",
      description:
        "Salame, palmito, cubos de presunto, mussarela, azeitona e tomate cereja",
      alt: "Tábua de frios",
      image: "22.png",
      price: "34.99",
    },
    {
      name: "326. Salame fatiado",
      description: "120 gramas",
      alt: "Salame fatiado",
      image: "23.png",
      price: "15.99",
    },
    {
      name: "327. Azeitonas verdes s/caroço",
      description: "200 gramas",
      alt: "Azeitonas verdes s/caroço",
      image: "24.png",
      price: "10.99",
    },
    {
      name: "Adicionais",
      description: "Pão fatiado ",
      alt: "sem imagem",
      image: "semimagem.png",
      price: "2.99",
    },
    {
      name: "Adicionais",
      description: "Molho especial e vinagrete",
      alt: "sem imagem",
      image: "semimagem.png",
      price: "1.99",
    },
  ],
  lanchesBaguete: [
    {
      name: "401. Girassóis ",
      description: "Filé mignon, queijo prato, azeitona preta e alface",
      alt: "Girassóis ",
      image: "semimagem.png",
      price: "27.99",
    },
    {
      name: "402. Gardênias",
      description: "Filé mignon, queijo prato, presunto e alface",
      alt: "Gardênias",
      image: "semimagem.png",
      price: "27.99",
    },
    {
      name: "403. Alecrins",
      description: "Filé mignon, queijo prato, bacon e alface",
      alt: "Alecrins",
      image: "semimagem.png",
      price: "28.99",
    },
    {
      name: "404. Bromélias",
      description: "Filé mignon, queijo prato, gorgonzola e alface",
      alt: "Bromélias",
      image: "semimagem.png",
      price: "28.99",
    },
    {
      name: "405. Margaridas",
      description: "Frango grelhado, queijo prato e alface",
      alt: "Margaridas",
      image: "semimagem.png",
      price: "20.99",
    },
    {
      name: "406. Magnólias",
      description: "Frango grelhado, queijo prato, tomate seco e alface",
      alt: "Magnólias",
      image: "semimagem.png",
      price: "22.99",
    },
    {
      name: "407. Camélias",
      description: "Frango grelhado, queijo prato, bacon e alface",
      alt: "Camélias",
      image: "semimagem.png",
      price: "22.99",
    },
    {
      name: "409. Acácias",
      description: "Linguiça, queijo prato, vinagrete e alface",
      alt: "Acácias",
      image: "semimagem.png",
      price: "22.99",
    },
    {
      name: "Adicionais",
      description: "Fritas e molho especial",
      alt: "sem imagem",
      image: "semimagem.png",
      price: "9.99",
    },
  ],
  sobremesas: [
    {
      name: "491. Petit Gateu",
      description:
        "pequeno bolo de chocolate com casca e recheio cremoso, acompanhado de sorvete",
      alt: "Petit Gateu",
      image: "semimagem.png",
      price: "19.99",
    },
    {
      name: "490. Taça de sorvete",
      description:
        "2 bolas do mesmo sabor (chocolate, creme ou morango), chantilly, morango e calda",
      alt: "Taça de sorvete",
      image: "semimagem.png",
      price: "16.99",
    },
  ],
  bebidas: [
    {
      name: "114. Suco natural 350ml",
      description: "Laranja e limão",
      alt: "Suco natural 350ml",
      image: "37.png",
      price: "5.99",
    },
    {
      name: "115. Suco lata 290ml",
      description: "Uva, pêssego, maracujá e manga",
      alt: "Suco lata 290ml",
      image: "38.png",
      price: "5.99",
    },
    {
      name: "130.Coca cola ks",
      description: "290ml vidro",
      alt: "Coca cola ks 290ml",
      image: "39.png",
      price: "3.99",
    },
    {
      name: "131.Coca cola e coca cola zero",
      description: "350ml lata",
      alt: "Coca cola e coca cola zero 350ml",
      image: "40.png",
      price: "4.99",
    },
    {
      name: "132. Fanta laranja e fanta uva",
      description: "350ml lata",
      alt: "Fanta laranja e fanta uva 350ml",
      image: "41.png",
      price: "4.99",
    },
    {
      name: "133. Guaraná antarctica e guaraná zero",
      description: "350ml lata",
      alt: "Guaraná antarctica e guaraná zero 350ml",
      image: "42.png",
      price: "4.99",
    },
    {
      name: "134. ITUBAÍNA RETRÔ",
      description: "355ml vidro",
      alt: "ITUBAÍNA RETRÔ 355ML",
      image: "43.png",
      price: "3.99",
    },
    {
      name: "135. H2oH! Limão ou limoneto",
      description: "500ml pet",
      alt: "H2oH! Limão ou limoneto 500ml",
      image: "44.png",
      price: "5.99",
    },
    {
      name: "136. Red bull ",
      description: "250ml lata",
      alt: "Red bull 250ml",
      image: "45.png",
      price: "11.99",
    },
    {
      name: "137. Monster",
      description: "473ml lata",
      alt: "Monster 473ml",
      image: "46.png",
      price: "11.99",
    },
    {
      name: "138. Água",
      description: "500ml pet",
      alt: "Água 500ml",
      image: "47.png",
      price: "3.00",
    },
    {
      name: "136. Água com gás",
      description: "500ml pet",
      alt: "Água com gás 500ml",
      image: "48.png",
      price: "3.50",
    },
  ],
  cervejas: [
    {
      name: "101. Cerveja Original ",
      description: "De garrafa",
      alt: "Original garrafa",
      image: "49.png",
      price: "13.99",
    },
    {
      name: "102. Cerveja Amstel ",
      description: "De garrafa",
      alt: "Amstel garrafa",
      image: "50.png",
      price: "11.99",
    },
    {
      name: "103. Cerveja Brahma ",
      description: "De garrafa",
      alt: "Brahma garrafa",
      image: "51.png",
      price: "9.99",
    },
    {
      name: "104. Cerveja Eisenbahn ",
      description: "De garrafa",
      alt: "Eisenbahn garrafa",
      image: "52.png",
      price: "12.99",
    },
    {
      name: "105. Cerveja Heineken ",
      description: "De garrafa",
      alt: "Heineken garrafa",
      image: "53.png",
      price: "15.99",
    },
    {
      name: "106. Cerveja Império puro malte ",
      description: "De garrafa",
      alt: "Império puro malte garrafa",
      image: "54.png",
      price: "9.99",
    },
    {
      name: "107. Cerveja Skol ",
      description: "De garrafa",
      alt: "Skol garrafa",
      image: "55.png",
      price: "9.99",
    },
    {
      name: "108. Cerveja Budweiser ",
      description: "De garrafa",
      alt: "Budweiser garrafa",
      image: "56.png",
      price: "11.99",
    },
    {
      name: "109. Cerveja Beck's ",
      description: "De garrafa",
      alt: "Beck's garrafa",
      image: "57.png",
      price: "13.99",
    },
    {
      name: "110. Cerveja Stella artois",
      description: "De garrafa",
      alt: "Stella artois",
      image: "58.png",
      price: "13.99",
    },
    {
      name: "150. Cerveja Cerveja zero álcool ",
      description: "Long neck",
      alt: "Cerveja zero álcool long neck",
      image: "59.png",
      price: "7.99",
    },
    {
      name: "151. Cerveja Corona ",
      description: "Long neck",
      alt: "Corona long neck",
      image: "60.png",
      price: "9.99",
    },
    {
      name: "152. Cerveja Stella artois ",
      description: "Long neck",
      alt: "Stella artois long neck",
      image: "61.png",
      price: "7.99",
    },
    {
      name: "153. Cerveja Império ",
      description: "Long neck",
      alt: "Império long neck",
      image: "62.png",
      price: "5.99",
    },
    {
      name: "154. Cerveja Heineken ",
      description: "Long neck",
      alt: "Heineken long neck",
      image: "63.png",
      price: "8.99",
    },
    {
      name: "155. Cerveja Eisenbahn ",
      description: "Long neck",
      alt: "Eisenbahn long neck",
      image: "64.png",
      price: "6.99",
    },
    {
      name: "156. Cerveja Budweiser ",
      description: "Long neck",
      alt: "Budweiser long neck",
      image: "65.png",
      price: "6.99",
    },
    {
      name: "157. Cerveja Cerveja malzebier ",
      description: "Long neck",
      alt: "Cerveja malzebier long neck",
      image: "66.png",
      price: "6.99",
    },
    {
      name: "158. Cerveja Brahma duplo malte",
      description: "Long neck",
      alt: "Brahma duplo malte long neck",
      image: "67.png",
      price: "6.99",
    },
    {
      name: "159. Cerveja Beck's ",
      description: "Long neck",
      alt: "Beck's long neck",
      image: "68.png",
      price: "7.99",
    },
    {
      name: "160. Smirnoff ice 275ml",
      alt: "Smirnoff ice 275ml",
      image: "69.png",
      price: "7.99",
    },
    {
      name: "161. Skol beats GT",
      alt: "Skol beats GT",
      image: "70.png",
      price: "9.99",
    },
    {
      name: "162. Eisenbahn american IPA e PALE ALE",
      alt: "Eisenbahn american IPA e PALE ALE",
      image: "71.png",
      price: "7.99",
    },
    {
      name: "116. CDB",
      alt: "CDB",
      image: "72.png",
      price: "2.99",
    },
  ],
  drinks: [
    {
      name: "601.Aperol spritz",
      description: "aperol, espumante, e água com gás",
      alt: "APEROL SPRITZ",
      image: "73.png",
      price: "23.99",
    },
    {
      name: "602. Gin Tônica",
      description: "gin, suco de laranja, água tônica",
      alt: "GIN TÔNICA",
      image: "semimagem.png",
      price: "23.99",
    },
    {
      name: "603. Gin Grenadine",
      description: "gin, grenadine e água tônica",
      alt: "GIN GRENADINE",
      image: "semimagem.png",
      price: "24.99",
    },
    {
      name: "604. Gin Tropical",
      description: "gin com energético tropical",
      alt: "GIN TROPICAL",
      image: "76.png",
      price: "24.99",
    },
    {
      name: "605.Gin Imperatriz",
      description: "gin, espumante e licor de cassis",
      alt: "GIN IMPERATRIZ",
      image: "77.png",
      price: "24.99",
    },
    {
      name: "606. Sex on The Beach",
      description: "vodka, licor de pêssego, suco de laranja, grenadine e gelo",
      alt: "SEX ON THE BEACH",
      image: "78.png",
      price: "19.99",
    },
    {
      name: "607. Pina Colada",
      description:
        "rum, suco de abacaxi, leite de coco, leite condensado e gelo",
      alt: "PINA COLADA",
      image: "79.png",
      price: "21.99",
    },
    {
      name: "610. Espanhola",
      description: "batida de vinho com leite condesado",
      alt: "ESPANHOLA",
      image: "semimagem.png",
      price: "21.99",
    },
    {
      name: "611. Lagoa Azul",
      description: "vodka, curaçau blue, limão, soda e açucar",
      alt: "LAGOA AZUL",
      image: "81.png",
      price: "19.99",
    },
    {
      name: "613. Bombeirinho",
      description: "cachaça, morango, limão e groselha",
      alt: "BOMBEIRINHO",
      image: "82.png",
      price: "18.99",
    },
    {
      name: "615. Margarita",
      description: "tequila, licor de laranja, suco de limão e sal",
      alt: "MARGARITA",
      image: "83.png",
      price: "29.99",
    },
    {
      name: "616. Mojito",
      description: "rum, suco de limão, açucar, água com gás e hortelã",
      alt: "MOJITO",
      image: "semimagem.png",
      price: "21.99",
    },
    {
      name: "617. Drinks Não Alcoólicos",
      description: "soda italiana, sex on the beach, pina colada e mojito",
      alt: "DRINKS NÃO ALCOÓLICOS",
      image: "semimagem.png",
      price: "12.99",
    },
  ],
  caipirinhas: [
    {
      name: "501. Cachaça",
      description: "Caipirinha de cachaça",
      alt: "Cachaça ",
      image: "semimagem.png",
      price: "17.99",
    },
    {
      name: "502. Vodka nacional smirnoff",
      description: "Caipirinha de Vodka nacional smirnoff",
      alt: "Vodka nacional smirnoff",
      image: "semimagem.png",
      price: "21.99",
    },
    {
      name: "503. Vodka importada absolut",
      description: "Caipirinha de Vodka importada absolut",
      alt: "Vodka importada absolut",
      image: "semimagem.png",
      price: "23.99",
    },
    {
      name: "504. Saquê",
      description: "Caipirinha de Saquê",
      alt: "Saquê",
      image: "semimagem.png",
      price: "21.99",
    },
    {
      name: "505. Especial da casa",
      description: "Servido na taça, vodka smirnoff, abacaxi, limão e hortelã",
      alt: "Especial da casa",
      image: "semimagem.png",
      price: "25.99",
    },
    {
      name: "Adicional",
      description: "Adicional de mais 1 fruta ",
      alt: "sem foto",
      image: "semimagem.png",
      price: "2.00",
    },
  ],
  doses: [
    {
      name: "701. Cachaça",
      description: "SÃO FRANCISCO OU VELHO BARREIRO",
      alt: "CACHAÇA",
      image: "92.png",
      price: "5.99",
    },
    {
      name: "702. Cachaça ESPECIAL",
      description: "SALINAS, NEFA FULÔ E SELETA",
      alt: "CACHAÇA ESPECIAL",
      image: "93.png",
      price: "7.99",
    },
    {
      name: "703. Tequila",
      description: "JOSÉ CUERVO OURO OU PRATA",
      alt: "TEQUILA",
      image: "94.png",
      price: "12.99",
    },
    {
      name: "704. Vodka Smirnoff",
      description: "Dose de vodka smirnoff",
      alt: "VODKA SMIRNOFF",
      image: "95.png",
      price: "11.99",
    },
    {
      name: "705. Vodka Absolut",
      description: "Dose de vodka absolut",
      alt: "VODKA ABSOLUT",
      image: "96.png",
      price: "13.99",
    },
    {
      name: "706. Conhaque Domeq",
      description: "Dose de conhaque domeq",
      alt: "CONHAQUE DOMEQ",
      image: "97.png",
      price: "9.99",
    },
    {
      name: "707. Red Label",
      description: "Dose de red label",
      alt: "RED LABEL",
      image: "98.png",
      price: "13.99",
    },
    {
      name: "708. Jack Daniel's",
      description: "Dose de jack daniel's",
      alt: "JACK DANIEL'S",
      image: "99.png",
      price: "16.99",
    },
    {
      name: "709. Jack Honey",
      description: "Dose de jack honey",
      alt: "JACK HONEY",
      image: "100.png",
      price: "15.99",
    },
    {
      name: "710. Black Label",
      description: "Dose de black label",
      alt: "BLACK LABEL",
      image: "101.png",
      price: "17.99",
    },
  ],
  almoco: [
    {
      name: "8001. Picanha ao alho",
      description: "Meia porção",
      alt: "Picanha ao alho",
      image: "semimagem.png",
      price: "94.99",
    },
    {
      name: "800. Picanha ao alho",
      description: "Porção inteira",
      alt: "Picanha ao alho",
      image: "semimagem.png",
      price: "144.99",
    },
    {
      name: "8021. Picanha ao Catupiry",
      description: "Meia porção",
      alt: "Picanha ao Catupiry",
      image: "semimagem.png",
      price: "104.99",
    },
    {
      name: "802. Picanha ao Catupiry",
      description: "Porção inteira",
      alt: "Picanha ao Catupiry",
      image: "semimagem.png",
      price: "159.99",
    },
    {
      name: "8011. Picanha acebolada",
      description: "Meia porção",
      alt: "Picanha acebolada",
      image: "semimagem.png",
      price: "94.99",
    },
    {
      name: "801. Picanha acebolada",
      description: "Porção inteira",
      alt: "Picanha acebolada",
      image: "semimagem.png",
      price: "144.99",
    },
    {
      name: "8101. Isca de mignon acebolado",
      description: "Meia porção",
      alt: "Isca de mignon acebolado",
      image: "semimagem.png",
      price: "84.99",
    },
    {
      name: "810. Isca de mignon acebolado",
      description: "Porção inteira",
      alt: "Isca de mignon acebolado",
      image: "semimagem.png",
      price: "149.90",
    },
    {
      name: "811. Isca de mignon ao catupiry",
      description: "Meia porção",
      alt: "Isca de mignon ao catupiry",
      image: "semimagem.png",
      price: "104.99",
    },
    {
      name: "811. Isca de mignon ao catupiry",
      description: "Porção inteira",
      alt: "Isca de mignon ao catupiry",
      image: "semimagem.png",
      price: "159.99",
    },
    {
      name: "812. isca de mignon gratinado",
      description: "Refeição de isca de mignon gratinado",
      alt: "isca de mignon gratinado",
      image: "semimagem.png",
      price: "92.99",
    },
    {
      name: "831. Filé de frango à Parmeggiana",
      description: "Refeição de Filé de frango à Parmeggiana",
      alt: "Filé de frango à Parmeggiana",
      image: "semimagem.png",
      price: "89.99",
    },
    {
      name: "830. Filé de mignon à Parmeggiana",
      description: "Refeição de Filé de mignon à Parmeggiana",
      alt: "Filé de mignon à Parmeggiana",
      image: "semimagem.png",
      price: "99.99",
    },
    {
      name: "832. Filé de tilápia à Parmeggiana",
      description: "Refeição de Filé de tilápia à Parmeggiana",
      alt: "Filé de tilápia à Parmeggiana",
      image: "semimagem.png",
      price: "94.99",
    },
    {
      name: "8201. Isca de tilápia à milanesa",
      description: "Meia porção",
      alt: "Isca de tilápia à milanesa",
      image: "semimagem.png",
      price: "74.99",
    },
    {
      name: "820. Isca de tilápia à milanesa",
      description: "Porção inteira",
      alt: "Isca de tilápia à milanesa",
      image: "semimagem.png",
      price: "94.99",
    },
    {
      name: "481. Salada de folhas, tomate, cebola e palmito",
      description: "Prato de saladas",
      alt: "Salada de folhas, tomate, cebola e palmito",
      image: "semimagem.png",
      price: "16.99",
    },
    {
      name: "482 Salada de folhas, tomate, cebola e tomate seco",
      description: "Prato de saladas",
      alt: "Salada de folhas, tomate, cebola e tomate seco",
      image: "semimagem.png",
      price: "18.99",
    },
    {
      name: "840. Prato executivo de picanha",
      description: "Bife de Picanha ao alho, arroz, feijão, salada e fritas",
      alt: "Prato executivo de picanha",
      image: "semimagem.png",
      price: "31.99",
    },
    {
      name: "844. Prato executivo de Contra filé",
      description: "Bife de contra filé, arroz, feijão, salada e fritas",
      alt: "Prato executivo de Contra filé",
      image: "semimagem.png",
      price: "24.99",
    },
    {
      name: "843. Prato executivo de Filé de frango",
      description: "File de Frango grelhado, arroz, feijão, salada e fritas",
      alt: "Prato executivo de Filé de frango",
      image: "semimagem.png",
      price: "18.99",
    },
    {
      name: "848. Prato do dia (Consulte opção)",
      description: "DISPONÍVEL DE SEGUNDA A SEXTA",
      alt: "Prato do dia (Consulte opção)",
      image: "semimagem.png",
    },
    {
      name: "845. Prato executivo de Isca de tilápia à milanesa",
      description: "Isca de tilápia, arroz, feijão, salada e fritas",
      alt: "Prato executivo de Isca de tilápia à milanesa",
      image: "semimagem.png",
      price: "27.99",
    },
    {
      name: "847. Prato executivo de Parmeggiana de tilápia",
      description: "Tilápia à parmeggiana, arroz, salada e fritas",
      alt: "Prato executivo de Parmeggiana de tilápia",
      image: "semimagem.png",
      price: "31.99",
    },
    {
      name: "842.  Prato executivo de Parmeggiana de mignon",
      description: "Bife de mignon à parmeggiana, arroz, salada e fritas",
      alt: "Prato executivo de Parmeggiana de mignon",
      image: "semimagem.png",
      price: "28.99",
    },
    {
      name: "845. Prato executivo de Parmeggiana de frango",
      description: "Bife de Picanha ao alho, arroz, salada e fritas",
      alt: "Prato executivo de Parmeggiana de frango",
      image: "semimagem.png",
      price: "22.99",
    },
    {
      name: "FEIJOADA AOS SÁBADOS",
      description: "Prato de feijoada",
      alt: "FEIJOADA AOS SÁBADOS",
      image: "semimagem.png",
    },
    {
      name: "Acompanhamentos",
      description:
        "Arroz, salada, feijão, farofa, fritas ou mandioca ou torresmo",
      alt: "sem imagem",
      image: "semimagem.png",
    },
  ],
};
